# Generated by Django 3.0.6 on 2020-05-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0002_message_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
