# Generated by Django 3.0.6 on 2020-05-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0004_message_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='color',
            field=models.CharField(choices=[('BL', 'Blue'), ('RE', 'Red'), ('YE', 'Yellow'), ('WH', 'White')], default='BL', max_length=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(default='Anonymous User', max_length=25),
        ),
    ]
